# CRIANDO A MATRIZ PARA O TABULEIRO:

matriz_aspectos = [
    ["TENEBROSO", "TENEBROSO", "CLARO", "CONSAGRAÇÃO", "TENEBROSO", "TENEBROSO", "JULGAMENTO", "TENEBROSO", "JULGAMENTO", "TENEBROSO", "JULGAMENTO", "TENEBROSO"],
    ["TENEBROSO", "TENEBROSO", "JULGAMENTO", "CONSAGRAÇÃO", "JULGAMENTO", "TENEBROSO", "CLARO", "TENEBROSO", "CLARO", "ABISMO", "FUMOSO", "TENEBROSO"],
    ["TENEBROSO", "JULGAMENTO", "CLARO", "CONSAGRAÇÃO", "TENEBROSO", "JULGAMENTO", "CONSAGRAÇÃO", "TENEBROSO", "CLARO", "TENEBROSO", "FUMOSO", "TENEBROSO"],
    ["CLARO", "CLARO", "CLARO", "CONSAGRAÇÃO", "TENEBROSO", "CLARO", "CLARO", "CLARO", "TENEBROSO", "TENEBROSO", "FUMOSO", "ABISMO"],
    ["CLARO", "JULGAMENTO", "TENEBROSO", "CLARO", "JULGAMENTO", "TENEBROSO", "CONSAGRAÇÃO", "CLARO", "CLARO", "TENEBROSO", "CLARO", "TENEBROSO"],
    ["JULGAMENTO", "JULGAMENTO", "TENEBROSO", "CLARO", "ABISMO", "CLARO", "TENEBROSO", "CLARO", "CLARO", "TENEBROSO", "CLARO", "TENEBROSO"],
    ["CLARO", "JULGAMENTO", "TENEBROSO", "CLARO", "JULGAMENTO", "CLARO", "ABISMO", "CONSAGRAÇÃO", "RENDIÇÃO", "ABISMO", "CONSAGRAÇÃO", "CLARO"],
    ["CLARO", "JULGAMENTO", "CLARO", "CLARO", "TENEBROSO", "JULGAMENTO", "TENEBROSO", "CLARO", "JULGAMENTO", "CLARO", "CLARO", "CLARO"],
    ["TENEBROSO", "JULGAMENTO", "CLARO", "JULGAMENTO", "TENEBROSO", "CONDENAÇÃO", "TENEBROSO", "MASMORRA", "CLARO", "CLARO", "CLARO", "JULGAMENTO"],
    ["TENEBROSO", "JULGAMENTO", "CLARO", "JULGAMENTO", "TENEBROSO", "NULL", "TENEBROSO", "MASMORRA", "TENEBROSO", "CLARO", "TENEBROSO", "CLARO"],
    ["ABISMO", "FORTUNA", "CONSAGRAÇÃO", "JULGAMENTO", "FUMOSO", "CLARO", "CLARO", "NULL", "TENEBROSO", "FUMOSO", "TENEBROSO", "CLARO"],
    ["TENEBROSO", "MASMORRA", "JULGAMENTO", "RENDIÇÃO", "FUMOSO", "CLARO", "CLARO", "FORTUNA", "ABISMO", "AMAGO", "ABISMO", "CLARO"],
    ["TENEBROSO", "CLARO", "FORTUNA", "TENEBROSO", "JULGAMENTO", "JULGAMENTO", "CLARO", "NULL", "CLARO", "AMAGO", "TENEBROSO", "JULGAMENTO"],
    ["TENEBROSO", "JULGAMENTO", "FORTUNA", "CAOS", "FUMOSO", "CONSAGRAÇÃO", "CLARO", "NULL", "CLARO", "AMAGO", "CLARO", "TENEBROSO"],
    ["TENEBROSO", "CONSAGRAÇÃO", "FORTUNA", "JULGAMENTO", "JULGAMENTO", "CLARO", "CLARO", "CLARO", "JULGAMENTO", "FUMOSO", "CLARO", "TENEBROSO"],
    ["ABISMO", "FORTUNA", "NULL", "MUTILAÇÃO", "FUMOSO", "JULGAMENTO", "CLARO", "CLARO", "CLARO", "CLARO", "CONSAGRAÇÃO", "TENEBROSO"],
    ["CLARO", "MUTILAÇÃO", "JULGAMENTO", "MASMORRA", "FUMOSO", "FUMOSO", "CLARO", "CLARO", "CLARO", "JULGAMENTO", "CONSAGRAÇÃO", "TENEBROSO"],
    ["CLARO", "MUTILAÇÃO", "CLARO", "FUMOSO", "JULGAMENTO", "FUMOSO", "CLARO", "CONSAGRAÇÃO", "JULGAMENTO", "CLARO", "JULGAMENTO", "TENEBROSO"],
    ["CONSAGRAÇÃO", "MUTILAÇÃO", "CLARO", "FUMOSO", "AMAGO", "FUMOSO", "TENEBROSO", "JULGAMENTO", "JULGAMENTO", "CLARO", "JULGAMENTO", "MUTILAÇÃO"],
    ["CLARO", "MUTILAÇÃO", "CLARO", "FUMOSO", "FUMOSO", "AMAGO", "ABISMO", "CONSAGRAÇÃO", "AMAGO", "JULGAMENTO", "CONSAGRAÇÃO", "CONSAGRAÇÃO"],
    ["MUTILAÇÃO", "CLARO", "CLARO", "CLARO", "MUTILAÇÃO", "JULGAMENTO", "JULGAMENTO", "FUMOSO", "FUMOSO", "TENEBROSO", "CLARO", "CLARO"],
    ["MUTILAÇÃO", "CLARO", "CLARO", "CLARO", "MASMORRA", "FUMOSO", "CLARO", "JULGAMENTO", "FUMOSO", "ABISMO", "NULL", "CLARO"],
    ["MASMORRA", "CLARO", "TENEBROSO", "JULGAMENTO", "MASMORRA", "MUTILAÇÃO", "CLARO", "MASMORRA", "FUMOSO", "MUTILAÇÃO", "MUTILAÇÃO", "MUTILAÇÃO"],
    ["MUTILAÇÃO", "JULGAMENTO", "TENEBROSO", "CLARO", "NULL", "NULL", "CLARO", "NULL", "CONSAGRAÇÃO", "MASMORRA", "MASMORRA", "MASMORRA"],
    ["CLARO", "JULGAMENTO", "TENEBROSO", "CLARO", "NULL", "MASMORRA", "CLARO", "NULL", "CLARO", "NULL", "CLARO", "NULL"],
    ["CLARO", "CLARO", "ABISMO", "JULGAMENTO", "CLARO", "FORTUNA", "CLARO", "FORTUNA", "CLARO", "CAOS", "CLARO", "CLARO"],
    ["CLARO", "CONSAGRAÇÃO", "TENEBROSO", "CLARO", "JULGAMENTO", "FORTUNA", "CLARO", "MASMORRA", "JULGAMENTO", "CAOS", "NULL", "JULGAMENTO"],
    ["CLARO", "CLARO", "NULL", "CLARO", "RENDIÇÃO", "TENEBROSO", "NULL", "TENEBROSO", "CLARO", "CONDENAÇÃO", "CLARO", "JULGAMENTO"],
    ["JULGAMENTO", "TENEBROSO", "NULL", "NULL", "CLARO", "TENEBROSO", "NULL", "CAOS", "CLARO", "CAOS", "JULGAMENTO", "TENEBROSO"],
    ["NULL", "TENEBROSO", "MASMORRA", "MASMORRA", "CLARO", "TENEBROSO", "MASMORRA", "TENEBROSO", "JULGAMENTO", "TENEBROSO", "CLARO", "TENEBROSO"],
]



matriz_generos = [
    ["MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO"],
    ["MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO"],
    ["MASCULINO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO"],
    ["MASCULINO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO"],
    ["MASCULINO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO"],
    ["MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO"],
    ["MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO"],
    ["MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO"],
    ["FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO"],
    ["MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO"],
    ["MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO"],
    ["MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO"],
    ["MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO"],
    ["MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "FEMININO"],
    ["MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "FEMININO"],
    ["FEMININO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO"],
    ["FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO"],
    ["FEMININO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO"],
    ["FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO"],
    ["FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO"],
    ["FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO"],
    ["FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "MASCULINO"],
    ["MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "FEMININO", "FEMININO", "MASCULINO", "FEMININO", "MASCULINO"],
    ["MASCULINO", "FEMININO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO"],
    ["MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO"],
    ["MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO"],
    ["MASCULINO", "MASCULINO", "MASCULINO",	"FEMININO", "MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "FEMININO", "FEMININO"],
    ["MASCULINO", "MASCULINO", "FEMININO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO",	"MASCULINO", "MASCULINO", "FEMININO", "FEMININO"],
    ["MASCULINO", "MASCULINO", "FEMININO", "MASCULINO",	"MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO",	"MASCULINO", "MASCULINO", "FEMININO", "MASCULINO"],
    ["MASCULINO", "MASCULINO", "FEMININO", "MASCULINO",	"MASCULINO", "MASCULINO", "MASCULINO", "MASCULINO",	"MASCULINO", "MASCULINO", "FEMININO", "MASCULINO"]
]

# Criando a matriz completa
matriz_completa = []
for i in range(len(matriz_aspectos)):
    linha_completa = [(matriz_aspectos[i][j], matriz_generos[i][j]) for j in range(len(matriz_aspectos[i]))]
    matriz_completa.append(linha_completa)







